# Feature: interview-practice-partner, Property 8: Questions Are Tagged with the Session Role
"""Property-based tests for questions being tagged with the session role.

For any supported role, all questions generated during a session with that role
must have a ``question_type`` that is a valid ``QuestionType`` enum value (not
``None`` or invalid).  Additionally, questions generated by
``InterviewService.generate_question()`` for a given role must have an
appropriate ``question_type``.

Optionally: TECHNICAL questions are only generated for roles where technical
knowledge is relevant (e.g. SOFTWARE_ENGINEER).

Validates: Requirements 3.2
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from interview_practice_partner.domain.enums import QuestionType, Role, Stage
from interview_practice_partner.domain.models import Question, SessionState
from interview_practice_partner.services.interview import InterviewService

# ---------------------------------------------------------------------------
# Supported roles (excludes UNKNOWN which is not a real interview role)
# ---------------------------------------------------------------------------

_SUPPORTED_ROLES = [
    Role.SOFTWARE_ENGINEER,
    Role.SALES_REPRESENTATIVE,
    Role.RETAIL_ASSOCIATE,
]

# Valid question types for any role (all QuestionType enum values)
_ALL_VALID_QUESTION_TYPES = set(QuestionType)

# Roles where TECHNICAL questions are appropriate
_TECHNICAL_ROLES = {Role.SOFTWARE_ENGINEER}

# ---------------------------------------------------------------------------
# Shared strategies
# ---------------------------------------------------------------------------

_uuid_strategy = st.uuids().map(str)
_phone_strategy = st.from_regex(r"\+1[2-9]\d{9}", fullmatch=True)
_datetime_strategy = st.datetimes(timezones=st.just(timezone.utc))
_nonempty_text = st.text(min_size=1, max_size=200)
_supported_role_strategy = st.sampled_from(_SUPPORTED_ROLES)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _build_session_with_role(
    role: Role,
    questions: list[Question] | None = None,
) -> SessionState:
    """Build an INTERVIEW SessionState for the given role.

    Args:
        role: The supported role for this session.
        questions: Optional list of questions already in the session.

    Returns:
        A ``SessionState`` in the INTERVIEW stage with the given role.
    """
    now = datetime.now(tz=timezone.utc)
    return SessionState(
        session_id=str(uuid.uuid4()),
        phone_number="+12025551234",
        stage=Stage.INTERVIEW,
        role=role,
        questions=questions or [],
        responses=[],
        off_topic_count=0,
        consecutive_out_of_scope_count=0,
        clarification_turn_count=0,
        requested_short_session=False,
        feedback_report=None,
        is_complete=False,
        created_at=now,
        updated_at=now,
        completed_at=None,
        context_summary=None,
    )


def _make_interview_service() -> InterviewService:
    """Build an InterviewService with a mock LLM that returns a generic question text."""
    call_counter = {"n": 0}

    async def _mock_complete(*_args, **_kwargs) -> str:
        n = call_counter["n"]
        call_counter["n"] += 1
        return f"Tell me about a time you demonstrated skill {n + 1}."

    mock_llm = AsyncMock()
    mock_llm.complete.side_effect = _mock_complete

    mock_prompt_builder = MagicMock()
    mock_prompt_builder.build_question_generation_prompt.return_value = [
        {"role": "system", "content": "You are a professional interviewer."},
        {"role": "user", "content": "Generate an interview question."},
    ]

    mock_whisper = AsyncMock()
    mock_tts = AsyncMock()
    mock_audio_download = AsyncMock()

    return InterviewService(
        llm_client=mock_llm,
        prompt_builder=mock_prompt_builder,
        whisper_client=mock_whisper,
        tts_client=mock_tts,
        audio_download_client=mock_audio_download,
    )


def _question_type_strategy() -> st.SearchStrategy[QuestionType]:
    """Strategy that generates any valid QuestionType."""
    return st.sampled_from(list(QuestionType))


def _question_strategy(role: Role | None = None) -> st.SearchStrategy[Question]:
    """Build a Question strategy with a valid question_type."""
    return st.builds(
        Question,
        question_id=_uuid_strategy,
        text=_nonempty_text,
        question_type=_question_type_strategy(),
        asked_at=_datetime_strategy,
        skipped=st.booleans(),
    )


def _session_with_questions_strategy() -> st.SearchStrategy[tuple[Role, SessionState]]:
    """Strategy: a supported role paired with a session containing 1–10 questions."""
    return _supported_role_strategy.flatmap(
        lambda role: st.lists(
            _question_strategy(role),
            min_size=1,
            max_size=10,
        ).map(lambda questions: (role, _build_session_with_role(role, questions)))
    )


# ---------------------------------------------------------------------------
# Property 8a: All questions in a session have a valid question_type
# ---------------------------------------------------------------------------


@given(role_and_session=_session_with_questions_strategy())
@settings(max_examples=100)
def test_property_8a_all_questions_have_valid_question_type(
    role_and_session: tuple[Role, SessionState],
) -> None:
    """Property 8a: All questions in a session have a valid question_type.

    For any supported role, every question in the session must have a
    ``question_type`` that is a member of the ``QuestionType`` enum.
    No question may have a ``None`` or invalid ``question_type``.

    **Validates: Requirements 3.2**
    """
    role, session = role_and_session

    # Precondition: the session uses a supported role
    assert role in _SUPPORTED_ROLES, f"Strategy should only produce supported roles, got {role!r}"
    assert session.role == role, (
        f"Session role {session.role!r} does not match expected role {role!r}"
    )

    for question in session.questions:
        assert question.question_type is not None, (
            f"Question {question.question_id!r} has question_type=None "
            f"in a session with role={role!r}"
        )
        assert question.question_type in _ALL_VALID_QUESTION_TYPES, (
            f"Question {question.question_id!r} has invalid question_type="
            f"{question.question_type!r} (not a member of QuestionType enum) "
            f"in a session with role={role!r}"
        )


# ---------------------------------------------------------------------------
# Property 8b: generate_question assigns a valid question_type for any supported role
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
@given(
    role=_supported_role_strategy,
    num_questions=st.integers(min_value=1, max_value=10),
)
@settings(max_examples=100)
async def test_property_8b_generate_question_assigns_valid_question_type(
    role: Role,
    num_questions: int,
) -> None:
    """Property 8b: generate_question assigns a valid question_type for any supported role.

    For any supported role, calling ``InterviewService.generate_question()``
    must produce questions whose ``question_type`` is a valid ``QuestionType``
    enum value (not ``None`` or invalid).

    **Validates: Requirements 3.2**
    """
    session = _build_session_with_role(role)
    service = _make_interview_service()

    for _ in range(num_questions):
        await service.generate_question(session)

    assert len(session.questions) == num_questions, (
        f"Expected {num_questions} questions after {num_questions} generate_question "
        f"calls, but got {len(session.questions)}"
    )

    for question in session.questions:
        assert question.question_type is not None, (
            f"generate_question produced a question with question_type=None "
            f"for role={role!r}"
        )
        assert question.question_type in _ALL_VALID_QUESTION_TYPES, (
            f"generate_question produced a question with invalid question_type="
            f"{question.question_type!r} for role={role!r}"
        )


# ---------------------------------------------------------------------------
# Property 8c: generate_question cycles through BEHAVIOURAL, SITUATIONAL, TECHNICAL
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
@given(role=_supported_role_strategy)
@settings(max_examples=100)
async def test_property_8c_generate_question_cycles_through_main_types(
    role: Role,
) -> None:
    """Property 8c: generate_question cycles through the three main question types.

    For any supported role, calling ``generate_question`` at least 3 times
    must produce at least one BEHAVIOURAL, one SITUATIONAL, and one TECHNICAL
    question — demonstrating that the question type cycle covers all main types
    regardless of role.

    **Validates: Requirements 3.2**
    """
    session = _build_session_with_role(role)
    service = _make_interview_service()

    # Generate 3 questions — enough to cover one full cycle
    for _ in range(3):
        await service.generate_question(session)

    assert len(session.questions) == 3, (
        f"Expected 3 questions after 3 generate_question calls, "
        f"but got {len(session.questions)}"
    )

    types_present = {q.question_type for q in session.questions}

    assert QuestionType.BEHAVIOURAL in types_present, (
        f"Expected at least one BEHAVIOURAL question after 3 generate_question "
        f"calls for role={role!r}, but found types: {types_present!r}"
    )
    assert QuestionType.SITUATIONAL in types_present, (
        f"Expected at least one SITUATIONAL question after 3 generate_question "
        f"calls for role={role!r}, but found types: {types_present!r}"
    )
    assert QuestionType.TECHNICAL in types_present, (
        f"Expected at least one TECHNICAL question after 3 generate_question "
        f"calls for role={role!r}, but found types: {types_present!r}"
    )


# ---------------------------------------------------------------------------
# Property 8d: TECHNICAL questions are only generated for technically-relevant roles
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
@given(num_questions=st.integers(min_value=5, max_value=10))
@settings(max_examples=100)
async def test_property_8d_technical_questions_generated_for_software_engineer(
    num_questions: int,
) -> None:
    """Property 8d: TECHNICAL questions are generated for SOFTWARE_ENGINEER role.

    When generating questions for the SOFTWARE_ENGINEER role, at least one
    TECHNICAL question must appear across a standard session (5–10 questions).
    This confirms that technical knowledge is assessed for roles where it is
    relevant.

    **Validates: Requirements 3.2**
    """
    role = Role.SOFTWARE_ENGINEER
    session = _build_session_with_role(role)
    service = _make_interview_service()

    for _ in range(num_questions):
        await service.generate_question(session)

    types_present = {q.question_type for q in session.questions}

    assert QuestionType.TECHNICAL in types_present, (
        f"Expected at least one TECHNICAL question for role={role!r} "
        f"after {num_questions} generate_question calls, "
        f"but found types: {types_present!r}"
    )


# ---------------------------------------------------------------------------
# Property 8e: question_type is never None for any question in any session
# ---------------------------------------------------------------------------


@given(
    role=_supported_role_strategy,
    questions=st.lists(
        st.builds(
            Question,
            question_id=_uuid_strategy,
            text=_nonempty_text,
            question_type=_question_type_strategy(),
            asked_at=_datetime_strategy,
            skipped=st.booleans(),
        ),
        min_size=0,
        max_size=15,
    ),
)
@settings(max_examples=100)
def test_property_8e_question_type_is_never_none(
    role: Role,
    questions: list[Question],
) -> None:
    """Property 8e: question_type is never None for any question in any session.

    For any supported role and any list of questions, every question must have
    a non-None ``question_type`` that is a valid ``QuestionType`` enum member.

    **Validates: Requirements 3.2**
    """
    session = _build_session_with_role(role, questions)

    for question in session.questions:
        assert question.question_type is not None, (
            f"Found question with question_type=None in session with role={role!r}. "
            f"Question id={question.question_id!r}, text={question.text!r}"
        )
        assert isinstance(question.question_type, QuestionType), (
            f"question_type must be a QuestionType instance, "
            f"got {type(question.question_type)!r} for question id={question.question_id!r}"
        )
        assert question.question_type in _ALL_VALID_QUESTION_TYPES, (
            f"question_type={question.question_type!r} is not a valid QuestionType value. "
            f"Valid values: {_ALL_VALID_QUESTION_TYPES!r}"
        )
